# Generated by Django 4.2.18 on 2025-01-22 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='activity_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='daily_goal',
            field=models.IntegerField(default=0),
        ),
    ]
