openapi: 3.0.3
info:
  title: ''
  version: 0.0.0
paths:
  /api/schema/:
    get:
      operationId: api_schema_retrieve
      description: |-
        OpenApi3 schema for this API. Format can be selected via content negotiation.

        - YAML: application/vnd.oai.openapi
        - JSON: application/vnd.oai.openapi+json
      parameters:
      - in: query
        name: format
        schema:
          type: string
          enum:
          - json
          - yaml
      - in: query
        name: lang
        schema:
          type: string
          enum:
          - af
          - ar
          - ar-dz
          - ast
          - az
          - be
          - bg
          - bn
          - br
          - bs
          - ca
          - ckb
          - cs
          - cy
          - da
          - de
          - dsb
          - el
          - en
          - en-au
          - en-gb
          - eo
          - es
          - es-ar
          - es-co
          - es-mx
          - es-ni
          - es-ve
          - et
          - eu
          - fa
          - fi
          - fr
          - fy
          - ga
          - gd
          - gl
          - he
          - hi
          - hr
          - hsb
          - hu
          - hy
          - ia
          - id
          - ig
          - io
          - is
          - it
          - ja
          - ka
          - kab
          - kk
          - km
          - kn
          - ko
          - ky
          - lb
          - lt
          - lv
          - mk
          - ml
          - mn
          - mr
          - ms
          - my
          - nb
          - ne
          - nl
          - nn
          - os
          - pa
          - pl
          - pt
          - pt-br
          - ro
          - ru
          - sk
          - sl
          - sq
          - sr
          - sr-latn
          - sv
          - sw
          - ta
          - te
          - tg
          - th
          - tk
          - tr
          - tt
          - udm
          - ug
          - uk
          - ur
          - uz
          - vi
          - zh-hans
          - zh-hant
      tags:
      - api
      security:
      - tokenAuth: []
      - {}
      responses:
        '200':
          content:
            application/vnd.oai.openapi:
              schema:
                type: object
                additionalProperties: {}
            application/yaml:
              schema:
                type: object
                additionalProperties: {}
            application/vnd.oai.openapi+json:
              schema:
                type: object
                additionalProperties: {}
            application/json:
              schema:
                type: object
                additionalProperties: {}
          description: ''
  /api/token/:
    post:
      operationId: api_token_create
      description: |-
        Takes a set of user credentials and returns an access and refresh JSON web
        token pair to prove the authentication of those credentials.
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenObtainPair'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TokenObtainPair'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/TokenObtainPair'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenObtainPair'
          description: ''
  /api/token/refresh/:
    post:
      operationId: api_token_refresh_create
      description: |-
        Takes a refresh type JSON web token and returns an access type JSON web
        token if the refresh token is valid.
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenRefresh'
          description: ''
  /api/v1/health-metrics/:
    get:
      operationId: api_v1_health_metrics_list
      description: A viewset for viewing and editing health metrics instances.
      tags:
      - Health Metrics
      security:
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/HealthMetrics'
          description: ''
    post:
      operationId: api_v1_health_metrics_create
      description: A viewset for viewing and editing health metrics instances.
      tags:
      - Health Metrics
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/HealthMetrics'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/HealthMetrics'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/HealthMetrics'
        required: true
      security:
      - tokenAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthMetrics'
          description: ''
  /api/v1/health-metrics/{id}/:
    get:
      operationId: api_v1_health_metrics_retrieve
      description: A viewset for viewing and editing health metrics instances.
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this health metrics.
        required: true
      tags:
      - Health Metrics
      security:
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthMetrics'
          description: ''
    put:
      operationId: api_v1_health_metrics_update
      description: A viewset for viewing and editing health metrics instances.
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this health metrics.
        required: true
      tags:
      - Health Metrics
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/HealthMetrics'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/HealthMetrics'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/HealthMetrics'
        required: true
      security:
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthMetrics'
          description: ''
    patch:
      operationId: api_v1_health_metrics_partial_update
      description: A viewset for viewing and editing health metrics instances.
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this health metrics.
        required: true
      tags:
      - Health Metrics
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedHealthMetrics'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedHealthMetrics'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedHealthMetrics'
      security:
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthMetrics'
          description: ''
    delete:
      operationId: api_v1_health_metrics_destroy
      description: A viewset for viewing and editing health metrics instances.
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this health metrics.
        required: true
      tags:
      - Health Metrics
      security:
      - tokenAuth: []
      responses:
        '204':
          description: No response body
  /api/v1/user-activities/:
    get:
      operationId: api_v1_user_activities_list
      description: A viewset for viewing and editing user activity instances.
      tags:
      - User Activities
      security:
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserActivity'
          description: ''
    post:
      operationId: api_v1_user_activities_create
      description: A viewset for viewing and editing user activity instances.
      tags:
      - User Activities
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserActivity'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/UserActivity'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/UserActivity'
        required: true
      security:
      - tokenAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserActivity'
          description: ''
  /api/v1/user-activities/{id}/:
    get:
      operationId: api_v1_user_activities_retrieve
      description: A viewset for viewing and editing user activity instances.
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this user activity.
        required: true
      tags:
      - User Activities
      security:
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserActivity'
          description: ''
    put:
      operationId: api_v1_user_activities_update
      description: A viewset for viewing and editing user activity instances.
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this user activity.
        required: true
      tags:
      - User Activities
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserActivity'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/UserActivity'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/UserActivity'
        required: true
      security:
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserActivity'
          description: ''
    patch:
      operationId: api_v1_user_activities_partial_update
      description: A viewset for viewing and editing user activity instances.
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this user activity.
        required: true
      tags:
      - User Activities
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedUserActivity'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedUserActivity'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedUserActivity'
      security:
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserActivity'
          description: ''
    delete:
      operationId: api_v1_user_activities_destroy
      description: A viewset for viewing and editing user activity instances.
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this user activity.
        required: true
      tags:
      - User Activities
      security:
      - tokenAuth: []
      responses:
        '204':
          description: No response body
components:
  schemas:
    HealthMetrics:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        user_id:
          type: string
          format: uuid
        date:
          type: string
          format: date
        heart_rate:
          type: integer
          maximum: 9223372036854775807
          minimum: -9223372036854775808
          format: int64
          nullable: true
        sleep_hours:
          type: number
          format: double
          nullable: true
        water_intake_liters:
          type: number
          format: double
          nullable: true
        weight_kg:
          type: number
          format: double
          nullable: true
      required:
      - date
      - id
      - user_id
    PatchedHealthMetrics:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        user_id:
          type: string
          format: uuid
        date:
          type: string
          format: date
        heart_rate:
          type: integer
          maximum: 9223372036854775807
          minimum: -9223372036854775808
          format: int64
          nullable: true
        sleep_hours:
          type: number
          format: double
          nullable: true
        water_intake_liters:
          type: number
          format: double
          nullable: true
        weight_kg:
          type: number
          format: double
          nullable: true
    PatchedUserActivity:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        user_id:
          type: string
          format: uuid
        date:
          type: string
          format: date
        steps:
          type: integer
          maximum: 9223372036854775807
          minimum: -9223372036854775808
          format: int64
        distance_km:
          type: number
          format: double
        calories_burned:
          type: number
          format: double
    TokenObtainPair:
      type: object
      properties:
        username:
          type: string
          writeOnly: true
        password:
          type: string
          writeOnly: true
        access:
          type: string
          readOnly: true
        refresh:
          type: string
          readOnly: true
      required:
      - access
      - password
      - refresh
      - username
    TokenRefresh:
      type: object
      properties:
        access:
          type: string
          readOnly: true
        refresh:
          type: string
          writeOnly: true
      required:
      - access
      - refresh
    UserActivity:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        user_id:
          type: string
          format: uuid
        date:
          type: string
          format: date
        steps:
          type: integer
          maximum: 9223372036854775807
          minimum: -9223372036854775808
          format: int64
        distance_km:
          type: number
          format: double
        calories_burned:
          type: number
          format: double
      required:
      - date
      - id
      - user_id
  securitySchemes:
    tokenAuth:
      type: apiKey
      in: header
      name: Authorization
      description: Token-based authentication with required prefix "Token"
